#FSR Autogenerated Content. DO NOT DELETE
from .operations import *
 
supported_operations = {
    'chat_completions': chat_completions,
    'list_models': list_models,
    'get_usage': get_usage
    }