#FSR Autogenerated Content. DO NOT DELETE
"""
Copyright start
MIT License
Copyright (c) 2024 Fortinet Inc
Copyright end
"""
from .operations import *
 
supported_operations = {
    'chat_completions': chat_completions,
    'chat_conversation': chat_completions,
    'list_models': list_models,
    'get_usage': get_usage,
    'count_tokens': count_tokens
    }